[pytest]
testpaths = .
python_files = test_*.py
norecursedirs =
    ipyleaflet_packages
    .ipynb_checkpoints
    data
    github_notebook_preview
markers =
    e2e: executes the complete Jupyter notebook and its installed dependencies.
